plugins {
    id 'multiloader-loader'
    alias(nyfs.plugins.loom.loader)
    alias(nyfs.plugins.regutils.loader)
    id("com.nyfaria.moddingtools.dependencies")
    id("com.nyfaria.moddingtools.publishing")
    id 'multiloader-fabric'
}

dependencies {
    modDeps.requiredMod(nyfs.geckolib.fabric, "geckolib", null)
    modDeps.requiredMod(nyfs.sbl.fabric, "smartbrainlib", null)
}
