# Project Specific
version=1.0.0
group=com.nyfaria
mod_name=NyfsMultiloader
mod_author=Nyfaria
mod_id=nyfsmultiloader
description=Multiloader Template Modified for the needs of Nyfaria.
credits=
curseforge_publishing_enabled=false
curseforge_project_id=0
modrinth_publishing_enabled=false
modrinth_project_id=0
dry_run=false

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Common
minecraft_version=1.21.8
java_version=21
license=ARR
