plugins {
    id 'multiloader-loader'
    alias(nyfs.plugins.mdg.loader)
    alias(nyfs.plugins.regutils.loader)
    id 'multiloader-moddev'
    id 'com.nyfaria.moddingtools.publishing'
    id("com.nyfaria.moddingtools.dependencies")
}

dependencies {
    modDeps.requiredMod(nyfs.geckolib.neoforge, "geckolib", null)
    modDeps.requiredMod(nyfs.sbl.neoforge, "smartbrainlib", null)
}
